#!/bin/bash

export DEBIAN_FRONTEND="noninteractive"

debconf-set-selections <<< "mysql-server mysql-server/root_password password admin123"
debconf-set-selections <<< "mysql-server mysql-server/root_password_again password admin123"
apt-get update && apt-get install -y mysql-server

